# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('travel_from', models.DateField()),
                ('travel_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people', models.ManyToManyField(related_name='usertravel', to='login_reg.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveller', to='login_reg.User')),
            ],
            managers=[
                ('TravelManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
