# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_bud', '0001_initial'),
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='travel',
            field=models.ManyToManyField(related_name='traveluser', to='travel_bud.Travel'),
        ),
    ]
